---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: restify
  namespace: parks-app
  labels:
    app: restify
spec:
  strategy:
    resources: {}
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - restify
      from:
        kind: ImageStreamTag
        name: "restify:latest"
  replicas: 1
  selector:
    app: restify
    deploymentconfig: restify
  template:
    metadata:
      creationTimestamp:
      labels:
        app: restify
        deploymentconfig: restify
    spec:
      volumes:
      - name: "restify-volume-1"
        emptyDir: {}
      containers:
      - name: restify
        image: library/restify:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DATABASE_SERVICE_NAME
          value: mongodb
        - name: MONGODB_DATABASE
          value: restify-database
        - name: MONGODB_PASSWORD
          value: mongo-user-password
        - name: MONGODB_USER
          value: mongo-user-1
        resources: {}
        volumeMounts:
        - name: "restify-volume-1"
          mountPath: "/run"
status: {}
